export const products = [
  {
    id: "kaju-katli",
    name: "Kaju Katli",
    price: 480,
    image: "/images/kaju-katli.jpg",
    description: "Premium diamond-shaped cashew fudge with silver leaf",
    category: "bestseller",
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    price: 320,
    image: "/images/gulab-jamun.jpg",
    description: "Soft milk dumplings soaked in rose-flavored sugar syrup",
    category: "bestseller",
  },
  {
    id: "rasmalai",
    name: "Rasmalai",
    price: 440,
    image: "/images/rasmalai.jpg",
    description: "Creamy cottage cheese discs in saffron-infused milk",
    category: "sweets",
  },
  {
    id: "rasgulla",
    name: "Rasgulla",
    price: 280,
    image: "/images/rasgulla.jpg",
    description: "Soft spongy cottage cheese balls in light sugar syrup",
    category: "sweets",
  },
  {
    id: "motichoor-laddu",
    name: "Motichoor Laddu",
    price: 360,
    image: "/images/motichoor-laddu.jpg",
    description: "Fragrant orange boondi balls with cardamom and saffron",
    category: "bestseller",
  },
  {
    id: "soan-papdi",
    name: "Soan Papdi",
    price: 250,
    image: "/images/soan-papdi.jpg",
    description: "Flaky layered sweet with cardamom and pistachio",
    category: "sweets",
  },
  {
    id: "milk-cake",
    name: "Milk Cake",
    price: 420,
    image: "/images/milk-cake.jpg",
    description: "Dense caramelized milk sweet with a grainy texture",
    category: "sweets",
  },
  {
    id: "peda",
    name: "Peda",
    price: 300,
    image: "/images/peda.jpg",
    description: "Traditional milk fudge discs with pistachio topping",
    category: "bestseller",
  },
  {
    id: "jalebi",
    name: "Jalebi",
    price: 240,
    image: "/images/jalebi.jpg",
    description: "Crispy golden spirals soaked in saffron sugar syrup",
    category: "sweets",
  },
  {
    id: "gajar-ka-halwa",
    name: "Gajar Ka Halwa",
    price: 380,
    image: "/images/gajar-ka-halwa.jpg",
    description: "Rich carrot pudding cooked with milk, ghee, and nuts",
    category: "sweets",
  },
  {
    id: "kalakand",
    name: "Kalakand",
    price: 460,
    image: "/images/kalakand.jpg",
    description: "Moist granular milk cake topped with pistachios",
    category: "sweets",
  },
  {
    id: "besan-laddu",
    name: "Besan Laddu",
    price: 340,
    image: "/images/besan-laddu.jpg",
    description: "Roasted gram flour balls with aromatic cardamom",
    category: "sweets",
  },
  {
    id: "malpua",
    name: "Malpua",
    price: 300,
    image: "/images/malpua.jpg",
    description: "Traditional pancakes soaked in syrup with rabri",
    category: "sweets",
  },
]
